name: 'Deploy / Create Release'

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Build Plugin Check
        run: npm run build

      - name: Set version
        run: echo "NEW_TAG_VERSION=${{ github.event.milestone.title }}" >> $GITHUB_ENV

      - name: Publish new tag
        run: |
          git tag $NEW_TAG_VERSION
          git push origin $NEW_TAG_VERSION

      - name: Run version update
        run: npm --no-git-tag-version version $NEW_TAG_VERSION

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $NEW_TAG_VERSION -n "${{ github.event.milestone.description }}" -t "$NEW_TAG_VERSION"

      - name: Upload asset to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload $NEW_TAG_VERSION build/plugin-check.zip