name: 'Deploy / Create Release'

on:
  milestone:
    types: [ closed ]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Set version
        run: |
          echo "NEW_TAG_VERSION=${{ github.event.milestone.title }}" >> $GITHUB_ENV

      - name: Validate tag version
        run: |
          MATCH='^([0-9]+\.){2}(\*|[0-9]+)(-.*)?$'
          if ! [[ $NEW_TAG_VERSION =~ $MATCH ]]; then
              echo "::error::Milestone title does not match semver format: '$NEW_TAG_VERSION'"
              exit 1
          fi
          
      - name: Update changelog.txt
        run: |
          echo -e "${{ github.event.milestone.title }} / $(date +%Y-%m-%d)\n===================\n${{ github.event.milestone.description }}\n\n$(cat changelog.txt)" > changelog.txt

      - name: Run version update
        run: |
          npm --no-git-tag-version version $NEW_TAG_VERSION
          npm run version

      - name: Build Plugin Check
        run: npm run build

      - name: Publish new tag
        run: |
          git tag $NEW_TAG_VERSION
          git push origin $NEW_TAG_VERSION

      - name: Push changes
        run: |
          git add -A .
          git commit -m "Updating to version $NEW_TAG_VERSION" --no-verify
          git push

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $NEW_TAG_VERSION -t "$NEW_TAG_VERSION"

      - name: Upload asset to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload $NEW_TAG_VERSION build/plugin-check.zip