name: 'Deploy / Create Pre-Release'

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Create pre-release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Append -beta onto the plugin version in the plugin header
        run: |
          ls -la
          sed -i '' 's/Version: .*/Version: '"$VERSION"-beta'/' class-plugin-check.php

      - name: Build Plugin Check
        run: npm run build

      - name: Set release version
        run: echo "RELEASE_VERSION=beta" >> $GITHUB_ENV

      - name: Upload asset to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload $RELEASE_VERSION build/plugin-check.zip --clobber