name: 'Deploy / Create Release'

on:
  push:
    branches:
      - 'main'

jobs:
  checkout:
    name: Checkout the ${{ github.event.repository.default_branch }} branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}

  release:
    runs-on: ubuntu-latest
    name: Create new release
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Build Plugin Check
        run: |
          npm run build

      - name: Set release version
        run: |
          echo "RELEASE_VERSION=beta" >> $GITHUB_ENV

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $RELEASE_VERSION -n "This is the beta version of Plugin Check with the latest changes. This is not an official release." -t "$RELEASE_VERSION" --prerelease

      - name: Upload asset to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload $RELEASE_VERSION build/plugin-check.zip